/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.Arrays;

/**
 *
 * @author darkn
 */
public class NewJFrame extends javax.swing.JFrame {
    
    
        public NewJFrame() 
        {
            initComponents();
        }

    /**
     * Creates new form NewJFrame
     */
    
    
    public void calculateGrades(){
        String score1 = course1enter.getText();
        String score2 = course2enter.getText();
        String score3 = course3enter.getText();
        String score4 = course4enter.getText();
        String score5 = course5enter.getText();
        String score6 = course6enter.getText();
        
        double creds1 = 0.0;
        String c1 = course1creds.getText();
        if (c1.length() > 0)
            creds1 = Double.parseDouble(course1creds.getText());
        
        double creds2 = 0.0;
        String c2 = course2creds.getText();
        if (c2.length() > 0);
            creds2 = Double.parseDouble(course2creds.getText());
        
        double creds3 = 0.0;
        String c3 = course3creds.getText();
        if (c3.length() > 0);
            creds3 = Double.parseDouble(course3creds.getText());
        
        double creds4 =0.0;
        String c4 = course4creds.getText();
        if (c4.length() > 0);
            creds4 = Double.parseDouble(course4creds.getText());
        
        double creds5 = 0.0;
        String c5 = course5creds.getText();
        if (c5.length() > 0);
            creds5 = Double.parseDouble(course5creds.getText());
           
        double creds6 = 0.0;
        String c6 = course6creds.getText();
        if (c6.length() > 0);
            creds6 = Double.parseDouble(course6creds.getText());

        double currentGPA = 0.0;
        String c7 = gpaenter.getText();
        if (c7.length() > 0)
            currentGPA = Double.parseDouble(gpaenter.getText());
        
        double currentCredits = 0.0;
        String c8 = creditenter.getText();
        if (c8.length() > 0)
            currentCredits = Double.parseDouble(creditenter.getText());
        double totalGPA = 0.0;
        
        double standingCreds = Double.parseDouble(creditenter.getText());
        double standingGPA = Double.parseDouble(gpaenter.getText());
        double totalCreds = creds1 + creds2 + creds3 + creds4 + creds5 + creds6;
        
        
        String[] grades = {score1, score2, score3, score4, score5, score6};
        double[] credits = {creds1, creds2, creds3, creds4, creds5, creds6};
        
        
        int [] baseGPAvals = new int[5];
        
        for (int i = 0; i < grades.length; i++){
            if (credits[i] == 0.0){
                continue;
            }
            else if (!(grades[i] instanceof String)){
                continue;
            }
            else if (grades[i].equals("A")){
                totalGPA += (4.0 * credits[i]);
            } else if (grades[i].equals("B+")) {
                totalGPA += (3.5 * credits[i]);
            } else if (grades[i].equals("B")) {
                totalGPA += (3.0 * credits[i]);
            } else if (grades[i].equals("C+")) {
                totalGPA += (2.5 * credits[i]);
            } else if (grades[i].equals("C"))
                totalGPA += (2.0 * credits[i]);
            System.out.println(Arrays.toString(baseGPAvals));
            }
        
        totalGPA += (standingGPA * standingCreds);
        double lastGPA = (totalGPA / (standingCreds + totalCreds));
        finalGPA.setText(String.valueOf(lastGPA));
        
        
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        course1 = new javax.swing.JLabel();
        course2 = new javax.swing.JLabel();
        course3 = new javax.swing.JLabel();
        course4 = new javax.swing.JLabel();
        course5 = new javax.swing.JLabel();
        course6 = new javax.swing.JLabel();
        course1enter = new javax.swing.JTextField();
        course2enter = new javax.swing.JTextField();
        course3enter = new javax.swing.JTextField();
        course4enter = new javax.swing.JTextField();
        course5enter = new javax.swing.JTextField();
        course6enter = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        credsApplied = new javax.swing.JLabel();
        creditenter = new javax.swing.JTextField();
        cumulativeGPA = new javax.swing.JLabel();
        gpaenter = new javax.swing.JTextField();
        finalGPALabel = new javax.swing.JLabel();
        finalGPA = new javax.swing.JLabel();
        course1creds = new javax.swing.JTextField();
        course2creds = new javax.swing.JTextField();
        course3creds = new javax.swing.JTextField();
        course4creds = new javax.swing.JTextField();
        course5creds = new javax.swing.JTextField();
        course6creds = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainLabel.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        mainLabel.setText("NJIT GPA Calculator");

        course1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        course1.setText("Course 1");

        course2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        course2.setText("Course 2");

        course3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        course3.setText("Course 3");

        course4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        course4.setText("Course 4");

        course5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        course5.setText("Course 5");

        course6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        course6.setText("Course 6");

        course1enter.setText("Enter Letter Grade");
        course1enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course1enterActionPerformed(evt);
            }
        });

        course2enter.setText("Enter Letter Grade");
        course2enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course2enterActionPerformed(evt);
            }
        });

        course3enter.setText("Enter Letter Grade");
        course3enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course3enterActionPerformed(evt);
            }
        });

        course4enter.setText("Enter Letter Grade");
        course4enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course4enterActionPerformed(evt);
            }
        });

        course5enter.setText("Enter Letter Grade");
        course5enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course5enterActionPerformed(evt);
            }
        });

        course6enter.setText("Enter Letter Grade");
        course6enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course6enterActionPerformed(evt);
            }
        });

        calculateButton.setBackground(new java.awt.Color(255, 0, 0));
        calculateButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        calculateButton.setForeground(new java.awt.Color(242, 242, 242));
        calculateButton.setText("Calculate!");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        credsApplied.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        credsApplied.setText("Credits Completed");

        creditenter.setText("Enter Creds");
        creditenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditenterActionPerformed(evt);
            }
        });

        cumulativeGPA.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        cumulativeGPA.setText("Cumulative GPA");

        gpaenter.setText("Enter GPA");
        gpaenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaenterActionPerformed(evt);
            }
        });

        finalGPALabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        finalGPALabel.setText("Final GPA");

        finalGPA.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        finalGPA.setText("0.00");

        course1creds.setText("Enter # of Credits");
        course1creds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course1credsActionPerformed(evt);
            }
        });

        course2creds.setText("Enter # of Credits");
        course2creds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course2credsActionPerformed(evt);
            }
        });

        course3creds.setText("Enter # of Credits");
        course3creds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course3credsActionPerformed(evt);
            }
        });

        course4creds.setText("Enter # of Credits");
        course4creds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course4credsActionPerformed(evt);
            }
        });

        course5creds.setText("Enter # of Credits");
        course5creds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course5credsActionPerformed(evt);
            }
        });

        course6creds.setText("Enter # of Credits");
        course6creds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course6credsActionPerformed(evt);
            }
        });

        jLabel1.setText("Please enter a value for each credit section.");

        jLabel2.setText("Grades Range from A+ -> C. Use Uppercase Values");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(course1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(course1enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(course1creds, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(course3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(course3enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(course3creds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(course5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(course5enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(course5creds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(finalGPALabel)
                                            .addGap(42, 42, 42)
                                            .addComponent(finalGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(course2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(course2enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(course2creds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(course4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(course4enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(course4creds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(course6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(course6enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(course6creds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cumulativeGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(credsApplied))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(creditenter, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(gpaenter)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(mainLabel)))
                .addGap(0, 152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(course1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(course1creds, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(course2)
                        .addComponent(course2enter, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(course2creds, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(course1enter, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course3enter, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course3creds, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course4)
                    .addComponent(course4enter, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course3)
                    .addComponent(course4creds, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course5)
                    .addComponent(course5enter, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course5creds, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course6)
                    .addComponent(course6enter, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course6creds, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cumulativeGPA)
                        .addComponent(finalGPALabel)
                        .addComponent(finalGPA))
                    .addComponent(gpaenter, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credsApplied)
                    .addComponent(creditenter, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void course1enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course1enterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course1enterActionPerformed

    private void course2enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course2enterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course2enterActionPerformed

    private void course3enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course3enterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course3enterActionPerformed

    private void course4enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course4enterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course4enterActionPerformed

    private void course5enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course5enterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course5enterActionPerformed

    private void course6enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course6enterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course6enterActionPerformed

    private void creditenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditenterActionPerformed

    private void gpaenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaenterActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        calculateGrades();
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void course1credsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course1credsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course1credsActionPerformed

    private void course2credsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course2credsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course2credsActionPerformed

    private void course3credsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course3credsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course3credsActionPerformed

    private void course4credsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course4credsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course4credsActionPerformed

    private void course5credsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course5credsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course5credsActionPerformed

    private void course6credsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course6credsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course6credsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel course1;
    private javax.swing.JTextField course1creds;
    private javax.swing.JTextField course1enter;
    private javax.swing.JLabel course2;
    private javax.swing.JTextField course2creds;
    private javax.swing.JTextField course2enter;
    private javax.swing.JLabel course3;
    private javax.swing.JTextField course3creds;
    private javax.swing.JTextField course3enter;
    private javax.swing.JLabel course4;
    private javax.swing.JTextField course4creds;
    private javax.swing.JTextField course4enter;
    private javax.swing.JLabel course5;
    private javax.swing.JTextField course5creds;
    private javax.swing.JTextField course5enter;
    private javax.swing.JLabel course6;
    private javax.swing.JTextField course6creds;
    private javax.swing.JTextField course6enter;
    private javax.swing.JTextField creditenter;
    private javax.swing.JLabel credsApplied;
    private javax.swing.JLabel cumulativeGPA;
    private javax.swing.JLabel finalGPA;
    private javax.swing.JLabel finalGPALabel;
    private javax.swing.JTextField gpaenter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mainLabel;
    // End of variables declaration//GEN-END:variables
}
